### PR TITLE
Added support for radio and checkbox inputs

### PR DESCRIPTION
**Pull request by ChinuxParibus**
Been built and tested across last versions of Chrome and Firefox (not been tested on IE)
Not been built the `dist/simple.css` and not minified yet

### CODE REVIEW

**Comment by jmjuanes** [comment]
Hello @ChinuxParibus . Thanks for your PR and sorry for the delay. 

Please, can you post here an example html using the radio and the checkbox styles of your PR? This will help me to test your changes. 

Thanks! :smile:

**Comment by ChinuxParibus** [comment]
Sure, I'm on it. Just let me pull the code on my own Github repo and I'll
send you the example, ok? ;)

2016-12-05 15:39 GMT-04:00 Josemi Juanes <notifications@github.com>:

**Comment by ChinuxParibus** [comment]
Hi, you can see the example here... It's been a long time so I couldn't
remember the syntax, but its siimple 😉

https://chinuxparibus.github.io/siimple/

P.D.: I forgot to make a PR to disabled checkbox & radio styles..., sorry 😌

2016-12-05 15:43 GMT-04:00 Jhony Grillet <grilletjhony@gmail.com>:

**Comment by jmjuanes** [comment]
Thanks for the example. I miss here the common "tick" for checkboxes, like this: 

image

You can view the code for this checkbox element [here](https://github.com/jviz/jviz/blob/dev/scss/components/_checkbox.scss) . 

I am working now on a big rewrite of this framework (Siimple 2.0), that will include checkboxes and radio inputs styles. So I think that we must wait and work for the new version, which will be available on this month!

**Comment by jmjuanes** [comment]
Hello! 

I just published the new v2.0.0, and this new version implements the checkbox element. Check the documentation: https://siimple.juanes.xyz/docs 

I am also working on the radio input.

Hope you like the new style! 😄

**Pull request closed without merging**
