### PR TITLE
Mobile Grid and better Input Classes

### PR DESCRIPTION
**Pull request by oltmannsdaniel**
Add the col-sm-* Class.
This grid class supports Mobile Devices (Screen smaller than 500px)
Remove the Transitions from Textarea.
Textarea only resize at vertical. Horizontal at 100% width unnecessary

### CODE REVIEW

**Comment by oltmannsdaniel** [comment]
@jmjuanes Maybe you add me to the Siimple organisation, so I can help you and we can start more Projects.

**Comment by jmjuanes** [comment]
Hi @oltmannsdaniel . Ok, welcome to the Siimple organisation!

**Comment by oltmannsdaniel** [comment]
@jmjuanes Thank you

**Comment by oltmannsdaniel** [comment]
@jmjuanes should I merge my branch with the original

**Comment by jmjuanes** [comment]
@oltmannsdaniel  Some comments about your pull request:
- I don't understand the `col-sm-*` class. Can you explain more about it?
- The other changes are perfect!

**Comment by oltmannsdaniel** [comment]
@jmjuanes With the col-sm-* class you can use grids for smaller device Screens than 500px.

col-sm-2 col-2 = 2 width column on All devices
col-2 = 2 column width only at Devices bigger than 500px
col-sm-2 = 2 column width at Mobile Devices (smaller than 500px)

**Comment by jmjuanes** [comment]
@oltmannsdaniel Perfect, merge now the branch :)

**Comment by oltmannsdaniel** [comment]
@jmjuanes I will update the reference tomorrow

**Comment by jmjuanes** [comment]
@oltmannsdaniel Ok. Now you can push directly to the repository. 
And if you want, please change your organization membership as public :)

**Comment by oltmannsdaniel** [comment]
@jmjuanes I change my Membership

**Pull request merged**
